services:
  mongodb:
    image: mongo:latest
    container_name: sps-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_DATABASE: sps

volumes:
  mongo-data:
